rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resource :retirements, only: %i[new create]
  
  resources :events, only: %i[new create show edit update destroy] do
    resources :tickets, only: %i[new create destroy]
  end

  get 'status' => 'status#index', defaults: { format: 'json' }

  match '*path' => 'application#error404', via: :all
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/models/event.rb
class Event < ApplicationRecord
  searchkick language: 'japanese'
  
  has_one_attached :image, dependent: false
  has_many :tickets, dependent: :destroy
  belongs_to :owner, class_name: 'User'

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_at, presence: true
  validates :end_at, presence: true
  validate :start_at_should_be_before_end_at
  validates :image,
            content_type: %i[png jpg jpeg],
            size: { less_than_or_equal_to: 10.megabytes },
            dimension: { width: { max: 2000 }, height: { max: 2000 } }

  attr_accessor :remove_image

  before_save :remove_image_if_user_accept

  def created_by?(user)
    return false unless user

    owner_id == user.id
  end

  def search_data
    {
      name: name,
      place: place,
      content: content,
      owner_name: owner&.name,
      start_at: start_at
    }
  end

  private

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    errors.add(:start_at, 'は終了より前に設定してください') if start_at >= end_at
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished
  
  has_many :created_events, class_name: 'Event', foreign_key: 'owner_id', dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event
  
  def self.find_or_create_from_auth_hash!(auth_hash)
    User.find_or_create_by!(provider: auth_hash[:provider], uid: auth_hash[:uid]) do |user|
      user.name = auth_hash[:info][:nickname]
      user.image_url = auth_hash[:info][:image]
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    if created_events.where(':now < end_at', now: now).exists?
      errors[:base] << '公開中の未終了イベントが存在します。'
    end

    if participating_events.where(':now < end_at', now: now).exists?
      errors[:base] << '未終了の参加イベントが存在します。'
    end

    throw(:abort) unless errors.empty?
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  helper_method :logged_in?, :current_user

  rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404
  
  private

  def logged_in?
    !!current_user
  end

  def current_user
    return unless session[:user_id]

    @current_user || User.find(session[:user_id])
  end

  def authenticate
    return if logged_in?

    redirect_to root_path, alert: 'ログインしてください'
  end

  def error404
    render 'error404', status: 404, formats: [:html]
  end

  def error500(error)
    logger.error [error, *error.backtrace].join('\n')
    render 'error500', status: 500, formats: [:html]
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate, only: :show
  
  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    redirect_to @event, notice: '作成しました' if @event.save
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event: @event)
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    redirect_to @event, notice: '変更しました' if @event.update(event_params)
  end

  def destroy
    current_user.created_events.find(params[:id]).destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(
      :name, :place, :image, :remove_image, :content, :start_at, :end_at
    )
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/retirements_controller.rb
class RetirementsController < ApplicationController
  def new
  end

  def create
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会終了しました'
    end
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: :create
  
  def create
    user = User.find_or_create_from_auth_hash!(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/status_controller.rb
class StatusController < ApplicationController
  skip_before_action :authenticate
  def index
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def new
    raise ActionController::RoutingError, 'ログイン状態でTicketsController#newにアクセス'
  end

  def create
    event = Event.find(params[:event_id])
    @ticket = current_user.tickets.build do |t|
      t.event = event
      t.comment = params[:ticket][:comment]
    end
    redirect_to event, notice: 'このイベントに参加表明しました' if @ticket.save
  end

  def destroy
    current_user.tickets.find_by!(event_id: params[:event_id]).destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate

  def index
    @event_search_form = EventSearchForm.new(event_search_form_params)
    @events = @event_search_form.search
  end

  def event_search_form_params
    params.fetch(:event_search_form, {}).permit(:keyword, :start_at).merge(page: params[:page])
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_github(user)
    "https://github.com/#{user.name}"
  end
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/helpers/events_helper.rb
module EventsHelper
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/helpers/retirements_helper.rb
module RetirementsHelper
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/helpers/tickets_helper.rb
module TicketsHelper
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/views/application/_errors.html.haml
.alert.alert-danger 
  %ul.mb-0
  - errors.full_messages.each do |message|
    %li= message

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/views/application/error404.html.haml
ご指定になったページは存在しません

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/views/application/error500.html.haml
エラーが発生しました

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title AwesomeEvents
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.navbar.navbar-expand-sm.navbar-light.bg-light
      .container
        = link_to 'AwesomeEvents', root_path, class: 'navbar-brand'
        %ul.navbar-nav
          %li.nav-item
            = link_to 'イベントを作る', new_event_path, class: 'nav-link'
          - if logged_in?
            %li.nav-item
              = link_to '退会', new_retirements_path, class: 'nav-link'
            %li.nav-item
              = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete
          - else
            %li.nav-item
              = link_to 'GitHubでログイン', '/auth/github', class: 'nav-link', method: :post
    .container
      - if flash.notice
        .alert.alert-success
          = flash.notice
      - if flash.alert
        .alert.alert-danger
          = flash.alert
      = yield

rails/chapter-6-awesome-events-chapter-7-application-testing-chapter-8-application-extension/awesome_events/app/views/welcome/index.html.haml
%h1 イベント一覧

= form_with(model: @event_search_form, url: root_path, method: :get) do |form|
  .form-group
    = form.label :keyword, 'キーワード'
    = form.text_field :keyword, class: 'form-control'
  .form-group
    = form.label :start_at, '以降に開催されるイベント'
    = form.datetime_field :start_at, class: 'form-control'
  .form-group
    = form.submit '検索', class: 'btn btn-primary'

%ul.list-group
  - @events.each do |event|
    = link_to(event, class: 'list-group-item list-group-item-action') do
      %h5.list-group-item-heading= event.name
      %p.mb-1= "#{l(event.start_at, format: :long)} - #{l(event.end_at, format: :long)}"

= paginate @events